name: Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn run build
    - name: Create .npmrc
      run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish
      run: |
        mv ./dist/src/index.js ./dist/src/index
        chmod +x ./dist/src/index
        mv ./README.md ./dist/README.md
        yarn publish ./dist --new-version ${GITHUB_REF#"refs/tags/"} --no-git-tag-version
